### PR TITLE
More dependency upgrades

### PR DESCRIPTION
**Pull request by huitseeker**
Those upgrades are submitted with the intent that dependabot does not suddenly start bombarding `libra/libra` with innocuous PRs.

### CODE REVIEW

**Comment by rexhoffman** [comment]
@huitseeker cool.   Dependabot will rebase the existing prs soon and begin closing them.   Another pretty nifty featur.

**Comment by rexhoffman** [comment]
@huitseeker doh, should have tested locally before merging.

   Compiling bytecode-verifier v0.1.0 (/home/rexhoffman/git/libra/language/bytecode-verifier)
error[E0599]: no method named `fill_bytes` found for type `rand::rngs::entropy::EntropyRng` in the current scope
   --> client/libra_wallet/src/mnemonic.rs:458:9
    |
458 |     rng.fill_bytes(&mut buf[..]);
    |         ^^^^^^^^^^ method not found in `rand::rngs::entropy::EntropyRng`
    |
    = help: items from traits can only be used if the trait is in scope
    = note: the following trait is implemented but not in scope; perhaps add a `use` for it:
            `use rand_core::RngCore;`

   Compiling libra-secure-net v0.1.0 (/home/rexhoffman/git/libra/secure/net)
warning: unused import: `rand_core::RngCore`
  --> client/libra_wallet/src/mnemonic.rs:17:5
   |
17 | use rand_core::RngCore;
   |     ^^^^^^^^^^^^^^^^^^
   |
   = note: `#[warn(unused_imports)]` on by default

error: aborting due to previous error

For more information about this error, try `rustc --explain E0599`.
error: could not compile `libra-wallet`.
warning: build failed, waiting for other jobs to finish...

**Comment by huitseeker** [comment]
@rexhoffman weird, I didn't manage to get the same result >_<
The following patch should fix it:
```rust
diff --git a/client/libra_wallet/Cargo.toml b/client/libra_wallet/Cargo.toml
index 4afe4820..be0583eb 100644
--- a/client/libra_wallet/Cargo.toml
+++ b/client/libra_wallet/Cargo.toml
@@ -12,7 +12,7 @@ edition = "2018"
 [dependencies]
 anyhow = "1.0"
 rand = "0.6.5"
-rand_core = "0.5.1"
+rand_core = "0.4.2"
 hex = "0.4.1"
 hmac = "0.7.1"
 byteorder = "1.3.2"
```

**Comment by huitseeker** [comment]
@rexhoffman Sorry about the trouble >_<

**Pull request merged**
